language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t cahitbeyaz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cahitbeyaz/react-test npm test

after_success:
  - docker build -t cahitbeyaz/multi-client ./client
  - docker build -t cahitbeyaz/multi-nginx ./nginx
  - docker build -t cahitbeyaz/multi-server ./server
  - docker build -t cahitbeyaz/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push cahitbeyaz/multi-nginx
  - docker push cahitbeyaz/multi-client
  - docker push cahitbeyaz/multi-server
  - docker push cahitbeyaz/multi-worker

deploy:
  provider: "elasticbeanstalk"
  region: "eu-west-3"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-3-406761548275"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ID
  secret_access_key:
    secure: $AWS_PWD
